services:
  postgres_delivery:
    image: postgres:16
    container_name: postgres_delivery
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: delivery_service
    ports:
      - "5556:5432"
    volumes:
      - delivery_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  delivery_service: 
    build: .
    depends_on:
        postgres_delivery:
            condition: service_healthy
    environment:
        - .env 
    ports:
        - "8000:8000"

volumes: 
  delivery_data: